---
title: "R Notebook"
output: html_notebook
---


```{r}
if(!require(devtools)) install.packages("devtools");require(devtools) 
if(!require(ggord)) install_github('fawda123/ggord');library(ggord)
if(!require(ggbiplot)) install_github("vqv/ggbiplot");require(ggbiplot) 
if(!require(ggord)) install_github('fawda123/ggord');require(ggord) 
if(!require(plotly)) install.packages("plotly");require(plotly) 
if(!require(rgl)) install.packages("rgl");require(rgl) 
if(!require(factoextra)) install.packages("factoextra");require(factoextra) 
if(!require(FactoMineR)) install.packages("FactoMineR");require(FactoMineR)
if(!require(plot3D)) install.packages("plot3D");require(plot3D) 

```



```{r}

julho2019 <- read.csv("Dados2/2019-julho.csv")

agosto2019 <- read.csv("Dados2/2019-agosto.csv")

setembro2019 <- read.csv("Dados2/2019-setembro.csv")

outubro2019 <- read.csv("Dados2/2019-outubro.csv")

novembro2019 <- read.csv("Dados2/2019-novembro.csv")

dezembro2019 <- read.csv("Dados2/2019-dezembro.csv")

```


```{r eval=FALSE, include=FALSE}
tabl=rbind(agosto2019,setembro2019,outubro2019,novembro2019,dezembro2019)
attach(tabl)
var=names(tabl)
```


```{r}
       
   var.omite=c(which(var=="slag_perc_pv"),
               which(var=="gypsum_perc_pv" ),
               which(var=="pozzolane_perc_pv" ),
               which(var=="clinker_perc_sp" ),
               which(var=="limestone_perc_sp" ),
               which(var=="slag_perc_sp" ),
               which(var=="slag_ton_h_pv" ),
               which(var=="gypsum_perc_sp" ),
               which(var=="pozzolane_perc_sp" ),
               which(var=="gypsum_ton_h_pv" ),
               which(var=="pozzolane_ton_h_pv" ),
               which(var=="slag_ton_h_sp" ),  
               which(var=="limestone_ton_h_sp" ),
               which(var=="clinker_ton_h_sp" ),
               which(var=="pozzolane_ton_h_sp"),
               which(var=="gypsum_ton_h_sp"),
               which(var=="fresh_air_damper_perc_pv "),
               which(var=="fresh_air_damper_perc_sp "),
               which(var=="moisture_gypsum_perc_pv"),
               which(var=="moisture_fly_ash_1_perc_pv"),
               which(var=="moisture_fly_ash_2_perc_pv"),
               which(var=="time_sample_taken_cpii_pv"),
               which(var=="cement_type_cpii_bool_pv"),
               which(var=="cement_type_cpiv_bool_pv"),
               which(var=="mill_operation"),
               which(var=="mill_operation"),
               which(var=="fan_speed_perc_sp"),
               which(var=="bf_dp_mbar_sp"),
               which(var=="limestone_perc_pv"),
               which(var=="is_enable_sp"),
               which(var=="mill_injection_water_perc_sp"),
               which(var=="mill_motor_pwr_kw_pv"),
               which(var=="bf_dp_mbar_pv"),
               which(var=="fresh_air_damper_perc_sp"),
               which(var=="fan_pwr_kw_pv"),
               which(var=="bf_out_press_mbar_pv"),
               which(var=="bf_dp_mbar_pv"),
               which(var=="grinding_pressure_bar_sp"),
               which(var=="grinding_pressure_bar_pv"),
               which(var=="bucket_elv_mtr_pwr_kw_pv"),
               which(var=="mill_in_press_mbar_sp"),
               which(var=="separator_speed_perc_sp"),
               which(var=="icon_bed_temp_c_sp"),
               which(var== "mill_injection_water_m3_h_pv"),
               which(var=="roller_1_bed_depth_mm_pv"),
               which(var=="roller_2_bed_depth_mm_pv"),
               which(var== "roller_3_bed_depth_mm_pv"),
               which(var=="mill_vibration_mm_s_pv"),
               which(var=="hopper_level_mg_m3_pv"),
                which(var=="clinker_perc_pv"),
 which(var=="total_feed_ton_h_pv"),
 which(var=="clinker_ton_h_pv"),
 which(var=="fan_speed_rpm_pv"),
 which(var=="gearbox_1_vibration_mm_s_pv"),
 which(var=="gearbox_2_vibration_mm_s_pv"),
 which(var=="grinding_aid_perc_sp"),
 which(var=="moisture_slag_perc_pv"),
 which(var=="moisture_pozzolane_perc_pv"),
 which(var=="moisture_clinker_perc_pv"),
 which(var=="moisture_limestone_perc_pv"),
  which(var== "total_feed_ton_h_sp"),
               which(var=="is_clicked_sp"))

flyash=c(which(var=="fly_ash_1_perc_pv" ),
          which(var=="fly_ash_2_perc_pv" ),
         which(var=="fly_ash_2_ton_h_sp" ),
         which(var=="fly_ash_1_ton_h_pv" ),
         which(var=="fly_ash_2_ton_h_pv"),
         which( var=="fly_ash_1_ton_h_sp"),
         which(var=="fly_ash_2_ton_h_sp"),
         which( var=="fly_ash_1_perc_sp"),
         which(var=="fly_ash_2_perc_sp"),
         which(var=="fresh_air_damper_perc_pv"))

id=c(1:2,var.omite,flyash)



```

Excluíndo observações entre coleta de cimento  e lançamento de observação de finura.

```{r eval=FALSE, include=FALSE}

df=data.frame(tabl[,-id])
dim(df)
attach(df)
varn=names(df)
idfine=which(varn=="fineness_perc_pv")
fin=df[,idfine]



```



```{r}
length(unique(fin))
sqn=numeric()
j=0
for(i in 2:nrow(df)){
  j=j+1
  if(FALSE==is.na(fin[i]) & FALSE==is.na(fin[i-1]) & fin[i]!=fin[i-1] & j>60){
     sq=(i-60):i;
     sqn=c(sqn,sq);
     j=0
     }
}
length(sqn)-length(unique(sqn))
dff=df[sqn,]
nrow(df)-nrow(dff);length(sqn)

```







```{r eval=FALSE, include=FALSE}

dfn=na.omit(dff)
 attach(dfn)
varn=names(dfn)
idfine=which(varn=="fineness_perc_pv")
fin=dfn[,idfine]


TT=length(fin)
seqq=1
r=1
for( i in 2:TT){
 if( fin[i]==fin[i-1]){seqq=c(seqq,r)}else{r=r+1;seqq=c(seqq,r)}
    }


```






```{r}
idi=which(total_feed_ton_h_pv>5 & total_feed_ton_h_pv<110& fly_ash_2_perc_pv>1)

```








```{r}
DT=numeric()
un=unique(seqq)
for(i in 1:length(un)){
M=colMeans(dfn[seqq==i,])
DT=rbind(DT,M)
}




```





```{r eval=FALSE, include=FALSE}
media = colMeans(DT)
media

desvioPadrao = apply(DT, 2, sd) 
desvioPadrao

dadosNorm=as.matrix(DT)

for(i in 1:length(desvioPadrao)){
   dadosNorm[,i] = (DT[,i]-media[i])/desvioPadrao[i]
}



```


 
 
```{r}
n=4
plot(DT[,n],DT[,IDF])
varnames=names(DT)
varnames[n]

```


* Normalização dos dados.


```{r eval=FALSE, include=FALSE}
DT=data.frame(DT)
 attach(DT)
varf=names(DT)
IDF=which(varf=="fineness_perc_pv")
fin=DT[,IDF]
categ=fin

categ[which(fin<2)]="A"
categ[which(fin >=2 & fin<=6)]="B"
categ[which(fin>6)]="C"


ind=c(3,5,8,9,10,13,14,28)

ind=c(2,10,13,14,28)

DFn=dadosNorm[,ind]

ord <- prcomp(DFn)
 
p <- ggord(ord, categ)
p
```



```{r eval=FALSE, include=FALSE}
DT=data.frame(DT)
 attach(DT)
varf=names(DT)
IDF=which(varf=="fineness_perc_pv")
fin=DT[,IDF]
categ=fin

categ[which(fin<2)]="red"
categ[which(fin >=2 & fin<=6)]="blue"
categ[which(fin>6)]="green"

res.pca=PCA(DFn, graph = FALSE)$ind
x=as.numeric(res.pca$coord[,1])
y=as.numeric(res.pca$coord[,2])
z=as.numeric(res.pca$coord[,3])



```





```{r}
plot_ly(type = "scatter3d",
        mode = "markers",
        swiss, x = x, y = y, z = z, 
        marker = list(color=categ, size = 4))
```





















